Update Kuber_cluster_monitoring.yml

diff --git a/.github/workflows/Kuber_cluster_monitoring.yml b/.github/workflows/Kuber_cluster_monitoring.yml
--- a/.github/workflows/Kuber_cluster_monitoring.yml
+++ b/.github/workflows/Kuber_cluster_monitoring.yml
@@ -28,4 +28,21 @@ jobs:
             kubectl --kubeconfig ~/.kube/config-k8s get pods -A > k8s_status.log
             kubectl config use-context k3s --kubeconfig ~/.kube/config-k3s
             kubectl --kubeconfig ~/.kube/config-k3s get pods -A > k3s_status.log
-        
+			    script: |
+            grep "failed" ~/k3s_status.log ~/k8s_status.log > Monitoring.txt || true
+            if [ -s Monitoring.txt ]; then
+              echo "failed=true" >> $GITHUB_ENV
+              cat Monitoring.txt
+            else
+              echo "failed=false" >> $GITHUB_ENV
+            fi
+			
+	   - name: Send message to Slack on Failure
+           if: env.failed == 'true'
+           run: |
+             curl -X POST -H 'Content-type: application/json' --data '{"text":"Failures found in your Kuber Cluster:\n'"$(cat Monitoring.txt)"'"}' ${{ secrets.HOOK }}
+
+       - name: Send message to Slack on Failure	
+           if: env.failed == 'false'	   
+		   run: |
+             curl -X POST -H 'Content-type: application/json' --data '{"text":"No Failures detected in your Kuber Cluster"}' ${{ secrets.HOOK }}
